### ISSUE TITLE
Windows wallet just closes when it reach block height=139377

### ISSUE THREAD

**Issue by TheMiningPool** [BlockStamp/bst#7]
Tried syncing from scratch several times, but everytime wallet autocloses at block height=139377
Any idea why?

**Comment by olkah** [comment]
it seems that this coin is created only for developers and their environment

**Comment by kuchtak** [comment]
Did you compile the code by yourself (which commit?) or downloaded binary version from https://blockstamp.info/download ?

**Comment by olkah** [comment]
I have no understanding how to create their miner

**Comment by kuchtak** [comment]
You may find a working cpuminer here https://github.com/BlockStamp/cpuminer.  Please remember that this topic is not about creating miners. We discuss here about a reported issue.

**Comment by TheMiningPool** [comment]
> 
> 
> Did you compile the code by yourself (which commit?) or download the binary version from https://blockstamp.info/download ?

Hi!
I used binaries from website. Tried with 64 and 32 bits version on 2 different machines with same results.
At the end I compiled the linux version from git and get it working fine, but no way with the windows versions.

**Comment by olkah** [comment]
This well but ordinary ASICs would still not as there is no production

**Comment by kuchtak** [comment]
This commit https://github.com/BlockStamp/bst/commit/b63b32c8e7f35d040df9d97cfd8a818852da2e2e should resolve the issue. Tomorrow we will release new Windows binaries.

**Comment by olkah** [comment]
how to make a normal extraction of asiks because you need to do sha256 mining only the usual of asiks !!

**Comment by olkah** [comment]
please fix it
no need to reinvent the wheel !!!!.

**Comment by kuchtak** [comment]
Normal (Bitcoin) ASICs are usless for blockstamp mining. Although they use the sha256 algorithm they create block with hashes started from 0. Blockstamp blocks starts from 8. We have nothing to fix here.

**Comment by TheMiningPool** [comment]
> 
> 
> This commit [b63b32c](https://github.com/BlockStamp/bst/commit/b63b32c8e7f35d040df9d97cfd8a818852da2e2e) should resolve the issue. Tomorrow we will release new Windows binaries.

ty!

**Comment by kuchtak** [comment]
Please check the nevest version of binaries.

**Comment by olkah** [comment]
Pool ???
